In [1]:
# Importing the libraries
import pandas as pd
import numpy as np

# Reading, loading and copying data

In [2]:
# Reading the dataset
data = pd.read_csv('Datasets/Toyota.csv')

In [3]:
# Making a copy of the dataset
df1 = data.copy(deep=True)

In [4]:
# Displaying the dataset
df1

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

# Understanding the dataset

In [5]:
# Displaying the first 5 rows
df1.head()

Unnamed: 0  Price   Age     KM FuelType  HP  MetColor  Automatic    CC  \
0           0  13500  23.0  46986   Diesel  90       1.0          0  2000   
1           1  13750  23.0  72937   Diesel  90       1.0          0  2000   
2           2  13950  24.0  41711   Diesel  90       NaN          0  2000   
3           3  14950  26.0  48000   Diesel  90       0.0          0  2000   
4           4  13750  30.0  38500   Diesel  90       0.0          0  2000   

   Doors  Weight  
0  three    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170

In [6]:
# Displaying the las 5 rows
df1.tail()

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

In [7]:
# Displaying the columns in the dataset
df1.columns

Index(['Unnamed: 0', 'Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor',
       'Automatic', 'CC', 'Doors', 'Weight'],
      dtype='object')

In [8]:
# Getting access to each of the column names of the dataset
for items in df1.columns:
    print(items)

Unnamed: 0
Price
Age
KM
FuelType
HP
MetColor
Automatic
CC
Doors
Weight


In [9]:
# Making changes to the column names
for items in df1.columns:
    print(items.upper())

UNNAMED: 0
PRICE
AGE
KM
FUELTYPE
HP
METCOLOR
AUTOMATIC
CC
DOORS
WEIGHT


In [10]:
# Accessing the values of the column by their label
df1['Price']

0       13500
1       13750
2       13950
3       14950
4       13750
        ...  
1431     7500
1432    10845
1433     8500
1434     7250
1435     6950
Name: Price, Length: 1436, dtype: int64

In [11]:
# Accessing a single value for a row and column by their label and index
sample = df1.at[1, 'Price']
print(sample) 

13750


In [12]:
# Displaying a single values for a row and column by using column interger and index
sample1 = df1.iat[1,1]
print(sample1)

13750


In [13]:
# Accessing multiple values for a row and a column by their label
df1.loc[0 : 15, 'Price']

0     13500
1     13750
2     13950
3     14950
4     13750
5     12950
6     16900
7     18600
8     21500
9     12950
10    20950
11    19950
12    19600
13    21500
14    22500
15    22000
Name: Price, dtype: int64

In [14]:
# Accessing multiple values for a row and columns using the column interger
df1.iloc[0 : 15, 1]

0     13500
1     13750
2     13950
3     14950
4     13750
5     12950
6     16900
7     18600
8     21500
9     12950
10    20950
11    19950
12    19600
13    21500
14    22500
Name: Price, dtype: int64

In [15]:
# Returnung the size of the dataset
df1.size

15796

In [16]:
# Returning the shape of the dataset
df1.shape

(1436, 11)

In [17]:
# Returning the number of rows and column in a print statement using thr f string
print(f'Total number of rows: {df1.shape[0]} \nTotal number of columns: {df1.shape[1]}')

Total number of rows: 1436 
Total number of columns: 11


In [18]:
# Calling a value from the shape of the dataset
df1.shape[0]

1436

In [19]:
# Returning the summary of the dataset
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [20]:
# Returns the columns and their types
df1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [21]:
# REturning the unique values in each column
df1.nunique()

Unnamed: 0    1436
Price          236
Age             77
KM            1256
FuelType         3
HP              13
MetColor         2
Automatic        2
CC              12
Doors            7
Weight          59
dtype: int64

In [22]:
# Returning the number of uniques values in Age
df1['Age'].unique()

array([23., 24., 26., 30., 32., 27., 25., 22., 31., 28., 29., nan, 20.,
       19., 17., 11., 18., 13., 14.,  4.,  8.,  7., 16., 15., 10., 12.,
        9.,  6.,  2.,  1., 43., 38., 40., 44., 41., 37., 39., 42., 35.,
       34., 33., 36., 53., 51., 54., 45., 55., 48., 52., 49., 56., 50.,
       47., 46., 58., 68., 59., 62., 65., 67., 64., 60., 61., 66., 57.,
       63., 73., 79., 78., 74., 77., 69., 80., 76., 70., 71., 75., 72.])

In [23]:
# Returns the number of uniques values in KM
df1['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [24]:
# Returns the number of uniques values in FuelType
df1['FuelType'].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [25]:
# Returns the number of uniques values in HP
df1['HP'].unique()

array(['90', '????', '192', '110', '97', '71', '116', '98', '69', '86',
       '72', '107', '73'], dtype=object)

In [26]:
# Returns the number of uniques values in MetColor
df1['MetColor'].unique()

array([ 1., nan,  0.])

In [27]:
# Returns the number of uniques values in Automatic
df1['Automatic'].unique()

array([0, 1])

In [28]:
# Returns the number of uniques values in CC
df1['CC'].unique()

array([2000, 1800, 1900, 1600, 1400, 1598, 1995, 1398, 1300, 1587, 1975,
       1332])

In [29]:
# Returns the number of uniques values in Doors
df1['Doors'].unique()

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [30]:
# Returns the number of uniques values in Weight
df1['Weight'].unique()

array([1165, 1170, 1245, 1185, 1105, 1065, 1120, 1100, 1255, 1270, 1110,
       1195, 1180, 1075, 1130, 1275, 1060, 1115, 1265, 1260, 1125, 1155,
       1045, 1480, 1320, 1280, 1135, 1090, 1150, 1085, 1160, 1205, 1084,
       1140, 1095, 1025, 1119, 1080, 1121, 1615, 1067, 1040, 1030, 1055,
       1050, 1103, 1070, 1035, 1015, 1000, 1078, 1079, 1109, 1020, 1010,
       1114, 1172, 1094, 1083])

In [31]:
# Returns the number of uniques values in Price
df1['Price'].unique()

array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,

In [32]:
# Returns the number of missing values in each column
df1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

# Data Preprocessing

In [33]:
# Replaces ???? with the appropriate missing value in numpy
df1['HP'] = df1['HP'].replace('????', np.nan)

In [34]:
df1['HP'].unique()

array(['90', nan, '192', '110', '97', '71', '116', '98', '69', '86', '72',
       '107', '73'], dtype=object)

In [35]:
# Replaces the three, four and five with integer
df1['Doors'] = df1['Doors'].replace('three', 3)
df1['Doors'] = df1['Doors'].replace('four', 4)
df1['Doors'] = df1['Doors'].replace('five', 5)

In [36]:
df1['Doors'].unique()

array([3, '3', '5', '4', 4, 5, '2'], dtype=object)

In [37]:
# Replace ?? with numpy missing values
df1['KM'] = df1['KM'].replace('??', np.nan)

In [38]:
df1['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [64]:
# Checks the types of the columns after the replace
df1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors           int64
Weight          int64
dtype: object

In [40]:
# Convert the column type to float
df1['HP'] = df1['HP'].astype('float64')

In [41]:
# Converting the column type into float
df1['KM'] = df1['KM'].astype('float64')

In [42]:
# Converting the column type into integer
df1['Doors'] = df1['Doors'].astype('int64')

In [43]:
df1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors           int64
Weight          int64
dtype: object

In [44]:
df1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [45]:
# Replaing the missing values in the HP with the mean
df1['HP'] = df1['HP'].fillna(df1['HP'].mean())

In [46]:
df1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [53]:
# Replacing missing values in Age with the mean
df1['Age'] = df1['Age'].fillna(df1['Age'].mean())

In [54]:
# Replacing missing values in KM with the mean
df1['KM'] = df1['KM'].fillna(df1['KM'].mean())

In [55]:
# Replacing missing values in MetColor with the median
df1['MetColor'] = df1['MetColor'].fillna(df1['MetColor'].median())

In [56]:
df1.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType      100
HP              0
MetColor        0
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [57]:
df1['FuelType'].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [58]:
# Replacing the missing value in FuelType with the highest count value
df1['FuelType'] = df1['FuelType'].fillna(df1['FuelType'].value_counts().index[0])

In [59]:
df1.isnull().sum()

Unnamed: 0    0
Price         0
Age           0
KM            0
FuelType      0
HP            0
MetColor      0
Automatic     0
CC            0
Doors         0
Weight        0
dtype: int64