# ASSGINMENT 
- Use the Toyota dataset to replication the codes above.
- Do that in a different notebook. 

# Importing libraries for loading and preprocessing 


In [2]:
import pandas as pd
import numpy as np


# Loading or Reading Dataset

In [3]:
pd.read_csv('Datasets/Toyota.csv')


Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

# Creating a variable for the dataset

In [4]:
Toyo = pd.read_csv('Datasets/Toyota.csv')
Toyo


Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

# Creating a Copy of Dataset

In [5]:
# Creating a deep copy of hte dataset (Toyo)
df1 = Toyo.copy(deep=True)


# Displaying the first five rows of the dataset, df1
df1.head()

# Displaying the last five rows of the dataset, df1
df1.tail()

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

In [6]:
#displaying n number of rows in data frame
df1.head(11)


Unnamed: 0  Price   Age     KM FuelType    HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel    90       1.0          0  2000   
1            1  13750  23.0  72937   Diesel    90       1.0          0  2000   
2            2  13950  24.0  41711   Diesel    90       NaN          0  2000   
3            3  14950  26.0  48000   Diesel    90       0.0          0  2000   
4            4  13750  30.0  38500   Diesel    90       0.0          0  2000   
5            5  12950  32.0  61000   Diesel    90       0.0          0  2000   
6            6  16900  27.0     ??   Diesel  ????       NaN          0  2000   
7            7  18600  30.0  75889      NaN    90       1.0          0  2000   
8            8  21500  27.0  19700   Petrol   192       0.0          0  1800   
9            9  12950  23.0  71138   Diesel  ????       NaN          0  1900   
10          10  20950  25.0  31461   Petrol   192       0.0          0  1800   

    Doors  Weight  
0   three    1165  
1       3    1165  
2       3    1165  
3       3    1165  
4       3    1170  
5       3    1170  
6       3    1245  
7       3    1245  
8       3    1185  
9       3    1105  
10      3    1185

In [7]:
# Returning the Size of the dataset
df1.size

# Checking the shape of the dataset using the formated string 
print(f'Total number of rows: {df1.shape[0]}, Total number of columns: {df1.shape[1]}')


Total number of rows: 1436, Total number of columns: 11


# Using the .info to return a concise summary of the dataset

In [8]:
df1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


# Checking the columns and their datatypes

In [9]:
df1.dtypes


Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

# Returning the number of unique values

In [10]:
df1.nunique()


Unnamed: 0    1436
Price          236
Age             77
KM            1256
FuelType         3
HP              13
MetColor         2
Automatic        2
CC              12
Doors            7
Weight          59
dtype: int64

# Unique values of each column

In [11]:
# Unique values for Price column
df1['Price'].unique()


array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,

In [12]:
# Unique values for Age column
df1['Age'].unique()


array([23., 24., 26., 30., 32., 27., 25., 22., 31., 28., 29., nan, 20.,
       19., 17., 11., 18., 13., 14.,  4.,  8.,  7., 16., 15., 10., 12.,
        9.,  6.,  2.,  1., 43., 38., 40., 44., 41., 37., 39., 42., 35.,
       34., 33., 36., 53., 51., 54., 45., 55., 48., 52., 49., 56., 50.,
       47., 46., 58., 68., 59., 62., 65., 67., 64., 60., 61., 66., 57.,
       63., 73., 79., 78., 74., 77., 69., 80., 76., 70., 71., 75., 72.])

In [13]:
# Unique values for KM column
df1['KM'].unique()


array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [14]:
# Unique values for FuelType column 
df1['FuelType'].unique()


array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [15]:
# Unique values for HP
df1['HP'].unique()


array(['90', '????', '192', '110', '97', '71', '116', '98', '69', '86',
       '72', '107', '73'], dtype=object)

In [16]:
# Unique values for MetColor
df1['MetColor'].unique()


array([ 1., nan,  0.])

In [17]:
# Unique values for Automatic column
df1['Automatic'].unique()


array([0, 1])

In [18]:
# Unique values for CC column
df1['CC'].unique()

array([2000, 1800, 1900, 1600, 1400, 1598, 1995, 1398, 1300, 1587, 1975,
       1332])

In [19]:
# Unique values for Doors column
df1['Doors'].unique()


array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [20]:
# Unique values for Weight column
df1['Weight'].unique()


array([1165, 1170, 1245, 1185, 1105, 1065, 1120, 1100, 1255, 1270, 1110,
       1195, 1180, 1075, 1130, 1275, 1060, 1115, 1265, 1260, 1125, 1155,
       1045, 1480, 1320, 1280, 1135, 1090, 1150, 1085, 1160, 1205, 1084,
       1140, 1095, 1025, 1119, 1080, 1121, 1615, 1067, 1040, 1030, 1055,
       1050, 1103, 1070, 1035, 1015, 1000, 1078, 1079, 1109, 1020, 1010,
       1114, 1172, 1094, 1083])

# Return the number of missing vlaues in each column

In [21]:
df1.isnull().sum()


Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

# Data Preprocessing 
- A. Replacing special characters 

In [22]:
# Replacing special characters in KM column
df1['KM'] = df1['KM'].replace('??', np.nan)


In [23]:
# Recheck for special character 
df1['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [24]:
# Replacing special characters in HP column
df1['HP'] = df1['HP'].replace('????', np.nan)


In [25]:
# Recheck for special character 
df1['HP'].unique()


array(['90', nan, '192', '110', '97', '71', '116', '98', '69', '86', '72',
       '107', '73'], dtype=object)

In [26]:
# Replacing special characters in Doors column
# First special character 'three'
df1['Doors'] = df1['Doors'].replace('three', '3')


In [27]:
# Recheck for special character 
df1['Doors'].unique()


array(['3', '5', '4', 'four', 'five', '2'], dtype=object)

In [28]:
# Replacing special characters in Doors column
# Second special character 'four'
df1['Doors'] = df1['Doors'].replace('four', '4')


In [29]:
# Recheck for special character 
df1['Doors'].unique()


array(['3', '5', '4', 'five', '2'], dtype=object)

In [30]:
# Replacing special characters in Doors column
# Third special character 'five'
df1['Doors'] = df1['Doors'].replace('five', '5')


In [31]:
# Recheck for special character 
df1['Doors'].unique()


array(['3', '5', '4', '2'], dtype=object)

# Data Preprocessing
- B. Converting the column types 

In [32]:
# Assigning the column KM to float using the astype
df1['KM'] = df1['KM'].astype('float64')


In [33]:
# rechecking data type for the column 
df1.dtypes 


Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [34]:
# Assigning the column HP to float using the astype
df1['HP'] = df1['HP'].astype('float64')


In [35]:
# rechecking data type for the column 
df1.dtypes


Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [36]:
# Assigning the column Doors to integer using the astype
df1['Doors'] = df1['Doors'].astype('int64')


In [37]:
# rechecking data type of the colummns 
df1.dtypes


Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors           int64
Weight          int64
dtype: object

# Rechecking for missing values in the data set

In [38]:
df1.isnull().sum()


Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

# Data Preprocessing
- C. Imputing the missing values 

In [39]:
# METCOLOR COLUMN
# fix or impute missing values for MetColor
# first compute the median
mdn_metcolor = df1 ['MetColor'].median()
print(mdn_metcolor)

# replacing missing valunes with the median using the .fillna function
df1['MetColor'] = df1 ['MetColor'].fillna(mdn_metcolor)


1.0


In [55]:
# KM COLUMN
# fix or impute missing values for MetColor
# first compute the mean
mean_km = df1 ['KM'].mean()
print(mean_km)

# replacing the missing values with the mean using .fillna function
df1['KM'] = df1 ['KM'].fillna(mean_km)


68647.23997185081


In [52]:
# HP COLUMN
# fix or impute missing values for MetColor
# first compute the mean
mean_hp = df1 ['HP'].mean()
print(mean_hp)

# replacing the missing values with the mean using the .fillna function
df1['HP'] = df1 ['HP'].fillna(mean_hp)


101.47832167832168


In [56]:
# AGE COLUMN
# fix or impute missing values for MetColor
# first compute the mean
mean_age = df1 ['Age'].mean()
print(mean_age)

# replacing the missing values with the mean age using the .fillna function
df1['Age'] = df1 ['Age'].fillna(mean_age)


55.67215568862275


In [47]:
# FuelType COLUMN
# fix or impute missing values for FuelType
# checking the number of counts 
df1['FuelType'].value_counts()

# selecting the value with the highest count
highest_count = df1['FuelType'].value_counts().index[0]

## replace the missing values in the column with the highest_count
df1['FuelType'] = df1['FuelType'].fillna(highest_count)


# Rechecking for missing values 

In [59]:
df1.isnull().sum()


Unnamed: 0    0
Price         0
Age           0
KM            0
FuelType      0
HP            0
MetColor      0
Automatic     0
CC            0
Doors         0
Weight        0
dtype: int64