In [23]:
import pandas as pd
import numpy as np

In [2]:
data1 = pd.read_csv("Datasets/Toyota.csv")
data1                            

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

## Reading/Creatng a copy of dataset

In [3]:
## Creating a deep copy of dataset
dt1 = data1.copy(deep=True)
dt1

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

In [4]:
## Displaying the first five rows
dt1.head()

Unnamed: 0  Price   Age     KM FuelType  HP  MetColor  Automatic    CC  \
0           0  13500  23.0  46986   Diesel  90       1.0          0  2000   
1           1  13750  23.0  72937   Diesel  90       1.0          0  2000   
2           2  13950  24.0  41711   Diesel  90       NaN          0  2000   
3           3  14950  26.0  48000   Diesel  90       0.0          0  2000   
4           4  13750  30.0  38500   Diesel  90       0.0          0  2000   

   Doors  Weight  
0  three    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170

In [5]:
## Displaying the first eight rows
dt1.head(8)

Unnamed: 0  Price   Age     KM FuelType    HP  MetColor  Automatic    CC  \
0           0  13500  23.0  46986   Diesel    90       1.0          0  2000   
1           1  13750  23.0  72937   Diesel    90       1.0          0  2000   
2           2  13950  24.0  41711   Diesel    90       NaN          0  2000   
3           3  14950  26.0  48000   Diesel    90       0.0          0  2000   
4           4  13750  30.0  38500   Diesel    90       0.0          0  2000   
5           5  12950  32.0  61000   Diesel    90       0.0          0  2000   
6           6  16900  27.0     ??   Diesel  ????       NaN          0  2000   
7           7  18600  30.0  75889      NaN    90       1.0          0  2000   

   Doors  Weight  
0  three    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170  
5      3    1170  
6      3    1245  
7      3    1245

In [6]:
## Displaying the last five rows
dt1.tail()

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

In [7]:
## Displaying the last nine rows
dt1.tail(9)

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1427        1427   8950   NaN  29000   Petrol   86       1.0          1  1300   
1428        1428   8450  72.0     ??   Petrol   86       NaN          0  1300   
1429        1429   8950  78.0  24000   Petrol   86       1.0          1  1300   
1430        1430   8450  80.0  23000   Petrol   86       0.0          0  1300   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1427     3    1045  
1428     3    1015  
1429     5    1065  
1430     3    1015  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

In [8]:
## Displaying the types of columns
dt1.columns

Index(['Unnamed: 0', 'Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor',
       'Automatic', 'CC', 'Doors', 'Weight'],
      dtype='object')

In [9]:
## Displaying all the types of columns in lower case
for each_item in dt1.columns:
    print(each_item.lower())

unnamed: 0
price
age
km
fueltype
hp
metcolor
automatic
cc
doors
weight


In [11]:
## Displaying all the types of columns in the upper case
for each_item in dt1.columns:
    print(each_item.upper())

UNNAMED: 0
PRICE
AGE
KM
FUELTYPE
HP
METCOLOR
AUTOMATIC
CC
DOORS
WEIGHT


In [16]:
## Displaying the values in a column
dt1["Age"]

0       23.0
1       23.0
2       24.0
3       26.0
4       30.0
        ... 
1431     NaN
1432    72.0
1433     NaN
1434    70.0
1435    76.0
Name: Age, Length: 1436, dtype: float64

In [19]:
## Accessing a single cell for a row or column by their index and label
dt1.at[1,"Age"]

np.float64(23.0)

In [22]:
dt1.iat[1,2]

np.float64(23.0)

In [24]:
## Accessing a group of rows and columns by their label
dt1.loc[1:15, "Age"]

1     23.0
2     24.0
3     26.0
4     30.0
5     32.0
6     27.0
7     30.0
8     27.0
9     23.0
10    25.0
11    22.0
12    25.0
13    31.0
14    32.0
15    28.0
Name: Age, dtype: float64

In [26]:
dt1.iloc[2,1]

np.int64(13950)

In [27]:
## Returns the shape of the dataset
dt1.shape

(1436, 11)

In [28]:
## Returns the size of the dataset
dt1.size

15796

In [30]:
print(f"Total number of rows: {dt1.shape[0]} , Total number of columns: {dt1.shape[1]}")

Total number of rows: 1436 , Total number of columns: 11


In [31]:
## Returns a concise summary of data
dt1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [34]:
## Returns columns and their types
dt1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [35]:
## Returns the number of unique value in each column
dt1.nunique()

Unnamed: 0    1436
Price          236
Age             77
KM            1256
FuelType         3
HP              13
MetColor         2
Automatic        2
CC              12
Doors            7
Weight          59
dtype: int64

In [36]:
## Returns the types of fuel in the column'FuelType'
dt1["FuelType"].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [38]:
dt1["Price"].unique()

array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,

In [39]:
dt1["MetColor"].unique()

array([ 1., nan,  0.])

In [40]:
dt1["Weight"].unique()

array([1165, 1170, 1245, 1185, 1105, 1065, 1120, 1100, 1255, 1270, 1110,
       1195, 1180, 1075, 1130, 1275, 1060, 1115, 1265, 1260, 1125, 1155,
       1045, 1480, 1320, 1280, 1135, 1090, 1150, 1085, 1160, 1205, 1084,
       1140, 1095, 1025, 1119, 1080, 1121, 1615, 1067, 1040, 1030, 1055,
       1050, 1103, 1070, 1035, 1015, 1000, 1078, 1079, 1109, 1020, 1010,
       1114, 1172, 1094, 1083])

In [41]:
## Return the number of missing numbers in each column
dt1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

### Data Preprocessing

In [52]:
## Replacing Special Characters
dt1["KM"] = dt1["KM"].replace("??" , np.nan)
dt1["KM"].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [54]:
## Converting column type to float
dt1["KM"].astype("float64")

0       46986.0
1       72937.0
2       41711.0
3       48000.0
4       38500.0
         ...   
1431    20544.0
1432        NaN
1433    17016.0
1434        NaN
1435        1.0
Name: KM, Length: 1436, dtype: float64

In [55]:
dt1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [57]:
dt1["KM"]=dt1["KM"].astype("float64")
dt1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [58]:
dt1["HP"]=dt1["HP"].replace("????", np.nan)
dt1["HP"].unique()

array(['90', nan, '192', '110', '97', '71', '116', '98', '69', '86', '72',
       '107', '73'], dtype=object)

In [59]:
dt1["HP"]=dt1["HP"].astype("float64")
dt1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [60]:
## Return the number of missing values in each column
dt1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [61]:
## Fix missing values for Age
mean_age = dt1["Age"].mean()
print(mean_age)

55.67215568862275


In [62]:
## Fill in the missing value using Fillna
dt1["Age"].fillna(mean_age)

0       23.000000
1       23.000000
2       24.000000
3       26.000000
4       30.000000
          ...    
1431    55.672156
1432    72.000000
1433    55.672156
1434    70.000000
1435    76.000000
Name: Age, Length: 1436, dtype: float64

In [63]:
dt1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [64]:
dt1["Age"] = dt1["Age"].fillna(mean_age)

In [65]:
dt1.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [66]:
dt1["KM"] = dt1["KM"].fillna(dt1["KM"].median())
dt1["HP"] = dt1["HP"].fillna(dt1["HP"].mean())
dt1["MetColor"] = dt1["MetColor"].fillna(dt1["MetColor"].median())

In [67]:
dt1.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType      100
HP              0
MetColor        0
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [68]:
## Fixing mising values for FuelType
dt1["FuelType"].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [69]:
dt1["FuelType"].value_counts().index[0]

'Petrol'

In [71]:
## Selecting the value with highest count and replacing it in the column
highest_count = dt1["FuelType"].value_counts().index[0]
dt1["FuelType"] = dt1["FuelType"].fillna(highest_count)

In [72]:
dt1.isnull().sum()

Unnamed: 0    0
Price         0
Age           0
KM            0
FuelType      0
HP            0
MetColor      0
Automatic     0
CC            0
Doors         0
Weight        0
dtype: int64