## Importing Libraries

In [2]:
## Importing Libraries such as pandas and numpy
import pandas as pd
import numpy as np

## Reading/Loading a Dataset

In [3]:
## Reading a Dataset Toyota
data = pd.read_csv('Datasets/Toyota.csv')
data

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

In [4]:
## Creating a deep copy of the dataset
## Using the head() to display the first 5 rows
## NB: df means DataFrame
df = data.copy(deep = True)
df.head()


Unnamed: 0  Price   Age     KM FuelType  HP  MetColor  Automatic    CC  \
0           0  13500  23.0  46986   Diesel  90       1.0          0  2000   
1           1  13750  23.0  72937   Diesel  90       1.0          0  2000   
2           2  13950  24.0  41711   Diesel  90       NaN          0  2000   
3           3  14950  26.0  48000   Diesel  90       0.0          0  2000   
4           4  13750  30.0  38500   Diesel  90       0.0          0  2000   

   Doors  Weight  
0  three    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170

In [5]:
## Creating a deep copy of the dataset
## Using the tail() to display the last 5 rows
df = data.copy(deep = True)
df.tail()


Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

## Using the for loop to create column of list in the dataset

In [6]:
## create a column of list
df.columns

Index(['Unnamed: 0', 'Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor',
       'Automatic', 'CC', 'Doors', 'Weight'],
      dtype='object')

In [7]:
## calling each list item in a column
df.columns
for each_items in df.columns:
    print(each_items)

Unnamed: 0
Price
Age
KM
FuelType
HP
MetColor
Automatic
CC
Doors
Weight


In [8]:
## calling each list item in a column and apply the lower()
df.columns
for each_items in df.columns:
    print(each_items.lower())

unnamed: 0
price
age
km
fueltype
hp
metcolor
automatic
cc
doors
weight


In [9]:
## Using for i in range() to retrieve items
df = data.copy(deep = True)
for i in range(1):
    print(df.iloc[i].head())

Unnamed: 0         0
Price          13500
Age             23.0
KM             46986
FuelType      Diesel
Name: 0, dtype: object


## Using Indexing to call out a column

In [10]:
## Indexing using square bracket []
df['Price']

0       13500
1       13750
2       13950
3       14950
4       13750
        ...  
1431     7500
1432    10845
1433     8500
1434     7250
1435     6950
Name: Price, Length: 1436, dtype: int64

In [11]:
## Indexing using the head()
df['Price'].head(10)

0    13500
1    13750
2    13950
3    14950
4    13750
5    12950
6    16900
7    18600
8    21500
9    12950
Name: Price, dtype: int64

In [12]:
## Access a single value for a row/column for their label and index
## using the .at[]:
df.at[3,'Price']          ## you call the row index first(2) and then the column label(Price)

np.int64(14950)

In [13]:
## Using the iat[].
## the i is an integer. 
df.iat[2,3]      ## Here,you first call the row index(2) and then the column index(3)

'41711'

In [14]:
## Using the loc[]: the loc[] is an indexing method that allows you to access and manipulate 
##specific rows and columns in a DataFrames based on their labels 
df.loc[1:10,'FuelType']

1     Diesel
2     Diesel
3     Diesel
4     Diesel
5     Diesel
6     Diesel
7        NaN
8     Petrol
9     Diesel
10    Petrol
Name: FuelType, dtype: object

In [15]:
## Using the iloc[]
df.iloc[1:10,4]         ## we access the rows and columns by integer position.

1    Diesel
2    Diesel
3    Diesel
4    Diesel
5    Diesel
6    Diesel
7       NaN
8    Petrol
9    Diesel
Name: FuelType, dtype: object

## Checking for the size and shape of the Dataset

In [16]:
## the size of the Dataset
df.size     ## it multiplies the the total rows and columns to return the overall size of the dataset

15796

In [17]:
## the shape of the Dataset
df.shape ## it returns the total rows which is 1436 and total columns which is 11.

(1436, 11)

## Using Formatting string to access columns and rows in Dataset

In [18]:
## Using the formatting string to return the total rows and columns
r = df.shape[0]
c = df.shape[1]
print(f"Total Number of Rows: {r}\nTotal Number of Columns: {c}")

Total Number of Rows: 1436
Total Number of Columns: 11


## Understanding more of the Dataset

In [19]:
## Using info() to return a concise summary of Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [20]:
## Using dtypes to return a column and its data type.
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [21]:
df.nunique() 

Unnamed: 0    1436
Price          236
Age             77
KM            1256
FuelType         3
HP              13
MetColor         2
Automatic        2
CC              12
Doors            7
Weight          59
dtype: int64

In [22]:
df['Price'].unique()

array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,

In [23]:
df['Age'].unique()

array([23., 24., 26., 30., 32., 27., 25., 22., 31., 28., 29., nan, 20.,
       19., 17., 11., 18., 13., 14.,  4.,  8.,  7., 16., 15., 10., 12.,
        9.,  6.,  2.,  1., 43., 38., 40., 44., 41., 37., 39., 42., 35.,
       34., 33., 36., 53., 51., 54., 45., 55., 48., 52., 49., 56., 50.,
       47., 46., 58., 68., 59., 62., 65., 67., 64., 60., 61., 66., 57.,
       63., 73., 79., 78., 74., 77., 69., 80., 76., 70., 71., 75., 72.])

In [24]:
df['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [25]:
df['FuelType'].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [26]:
df['HP'].unique()

array(['90', '????', '192', '110', '97', '71', '116', '98', '69', '86',
       '72', '107', '73'], dtype=object)

In [27]:
df['MetColor'].unique()

array([ 1., nan,  0.])

In [28]:
df['Automatic'].unique()

array([0, 1])

In [29]:
df['CC'].unique()

array([2000, 1800, 1900, 1600, 1400, 1598, 1995, 1398, 1300, 1587, 1975,
       1332])

In [30]:
df['Doors'].unique()

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [31]:
df['Weight'].unique()

array([1165, 1170, 1245, 1185, 1105, 1065, 1120, 1100, 1255, 1270, 1110,
       1195, 1180, 1075, 1130, 1275, 1060, 1115, 1265, 1260, 1125, 1155,
       1045, 1480, 1320, 1280, 1135, 1090, 1150, 1085, 1160, 1205, 1084,
       1140, 1095, 1025, 1119, 1080, 1121, 1615, 1067, 1040, 1030, 1055,
       1050, 1103, 1070, 1035, 1015, 1000, 1078, 1079, 1109, 1020, 1010,
       1114, 1172, 1094, 1083])

In [32]:
## Return the number of missing values in each column
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

## Data Preprocessing

In [33]:
## Using replace() to replace special characters in the Dataset
## Replacing value for the column label KM
## We are replacing the ?? in the KM column with nan value. 
## the false indicate that there is a missing a value and that is the nan. 
df['KM'].replace('??',np.nan,inplace = False)    

0       46986
1       72937
2       41711
3       48000
4       38500
        ...  
1431    20544
1432      NaN
1433    17016
1434      NaN
1435        1
Name: KM, Length: 1436, dtype: object

In [34]:
## rechecking that the relacement has taken place
## we assign the KM to the replace code
df["KM"] = df["KM"].replace("??",np.nan)

In [35]:
## confirming our checking
df["KM"].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [36]:
## This code will display the table very well for us to see the change that has taken place
df.head(20)

Unnamed: 0  Price   Age     KM FuelType    HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel    90       1.0          0  2000   
1            1  13750  23.0  72937   Diesel    90       1.0          0  2000   
2            2  13950  24.0  41711   Diesel    90       NaN          0  2000   
3            3  14950  26.0  48000   Diesel    90       0.0          0  2000   
4            4  13750  30.0  38500   Diesel    90       0.0          0  2000   
5            5  12950  32.0  61000   Diesel    90       0.0          0  2000   
6            6  16900  27.0    NaN   Diesel  ????       NaN          0  2000   
7            7  18600  30.0  75889      NaN    90       1.0          0  2000   
8            8  21500  27.0  19700   Petrol   192       0.0          0  1800   
9            9  12950  23.0  71138   Diesel  ????       NaN          0  1900   
10          10  20950  25.0  31461   Petrol   192       0.0          0  1800   
11          11  19950  22.0  43610   Petrol   192       0.0          0  1800   
12          12  19600  25.0  32189   Petrol   192       0.0          0  1800   
13          13  21500  31.0  23000   Petrol   192       1.0          0  1800   
14          14  22500  32.0  34131   Petrol   192       1.0          0  1800   
15          15  22000  28.0  18739   Petrol  ????       0.0          0  1800   
16          16  22750  30.0  34000   Petrol   192       1.0          0  1800   
17          17  17950  24.0  21716   Petrol   110       1.0          0  1600   
18          18  16750  24.0  25563   Petrol   110       0.0          0  1600   
19          19  16950  30.0  64359   Petrol   110       1.0          0  1600   

    Doors  Weight  
0   three    1165  
1       3    1165  
2       3    1165  
3       3    1165  
4       3    1170  
5       3    1170  
6       3    1245  
7       3    1245  
8       3    1185  
9       3    1105  
10      3    1185  
11      3    1185  
12      3    1185  
13      3    1185  
14      3    1185  
15      3    1185  
16      3    1185  
17      3    1105  
18      3    1065  
19      3    1105

In [37]:
## Using replace() to replace special characters in the Dataset
## Replacing value for the column label HP
## We are replacing the ???? in the HP column with nan value. 
## the false indicate that there is a missing a value and that is the nan.
df['HP'].replace('????',np.nan,inplace = False)

0        90
1        90
2        90
3        90
4        90
       ... 
1431     86
1432     86
1433     86
1434     86
1435    110
Name: HP, Length: 1436, dtype: object

In [38]:
df.head(20)

Unnamed: 0  Price   Age     KM FuelType    HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel    90       1.0          0  2000   
1            1  13750  23.0  72937   Diesel    90       1.0          0  2000   
2            2  13950  24.0  41711   Diesel    90       NaN          0  2000   
3            3  14950  26.0  48000   Diesel    90       0.0          0  2000   
4            4  13750  30.0  38500   Diesel    90       0.0          0  2000   
5            5  12950  32.0  61000   Diesel    90       0.0          0  2000   
6            6  16900  27.0    NaN   Diesel  ????       NaN          0  2000   
7            7  18600  30.0  75889      NaN    90       1.0          0  2000   
8            8  21500  27.0  19700   Petrol   192       0.0          0  1800   
9            9  12950  23.0  71138   Diesel  ????       NaN          0  1900   
10          10  20950  25.0  31461   Petrol   192       0.0          0  1800   
11          11  19950  22.0  43610   Petrol   192       0.0          0  1800   
12          12  19600  25.0  32189   Petrol   192       0.0          0  1800   
13          13  21500  31.0  23000   Petrol   192       1.0          0  1800   
14          14  22500  32.0  34131   Petrol   192       1.0          0  1800   
15          15  22000  28.0  18739   Petrol  ????       0.0          0  1800   
16          16  22750  30.0  34000   Petrol   192       1.0          0  1800   
17          17  17950  24.0  21716   Petrol   110       1.0          0  1600   
18          18  16750  24.0  25563   Petrol   110       0.0          0  1600   
19          19  16950  30.0  64359   Petrol   110       1.0          0  1600   

    Doors  Weight  
0   three    1165  
1       3    1165  
2       3    1165  
3       3    1165  
4       3    1170  
5       3    1170  
6       3    1245  
7       3    1245  
8       3    1185  
9       3    1105  
10      3    1185  
11      3    1185  
12      3    1185  
13      3    1185  
14      3    1185  
15      3    1185  
16      3    1185  
17      3    1105  
18      3    1065  
19      3    1105

In [39]:
## rechecking that the relacement has taken place
## we assign the KM to the replace code
df["HP"] = df["HP"].replace("????",np.nan)

In [40]:
## confirming our checking
df['HP'].unique()

array(['90', nan, '192', '110', '97', '71', '116', '98', '69', '86', '72',
       '107', '73'], dtype=object)

In [41]:
## This code will display the table very well for us to see the change that has taken place
df.head(20)

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1            1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2            2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3            3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4            4  13750  30.0  38500   Diesel   90       0.0          0  2000   
5            5  12950  32.0  61000   Diesel   90       0.0          0  2000   
6            6  16900  27.0    NaN   Diesel  NaN       NaN          0  2000   
7            7  18600  30.0  75889      NaN   90       1.0          0  2000   
8            8  21500  27.0  19700   Petrol  192       0.0          0  1800   
9            9  12950  23.0  71138   Diesel  NaN       NaN          0  1900   
10          10  20950  25.0  31461   Petrol  192       0.0          0  1800   
11          11  19950  22.0  43610   Petrol  192       0.0          0  1800   
12          12  19600  25.0  32189   Petrol  192       0.0          0  1800   
13          13  21500  31.0  23000   Petrol  192       1.0          0  1800   
14          14  22500  32.0  34131   Petrol  192       1.0          0  1800   
15          15  22000  28.0  18739   Petrol  NaN       0.0          0  1800   
16          16  22750  30.0  34000   Petrol  192       1.0          0  1800   
17          17  17950  24.0  21716   Petrol  110       1.0          0  1600   
18          18  16750  24.0  25563   Petrol  110       0.0          0  1600   
19          19  16950  30.0  64359   Petrol  110       1.0          0  1600   

    Doors  Weight  
0   three    1165  
1       3    1165  
2       3    1165  
3       3    1165  
4       3    1170  
5       3    1170  
6       3    1245  
7       3    1245  
8       3    1185  
9       3    1105  
10      3    1185  
11      3    1185  
12      3    1185  
13      3    1185  
14      3    1185  
15      3    1185  
16      3    1185  
17      3    1105  
18      3    1065  
19      3    1105

In [42]:
## Checking for the label with a missing value
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

## Imputing / Fixing the Missing Values for the column labels in the Dataset

In [43]:
## Checking for the datatype of the dataframe
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [44]:
## Imputing / fixing the missing value for Column Label[Age] 
## We are using the function fillna()
## The datatype for Age is float, therefore we will use mean to find the average of Age column
df['Age'].mean()

np.float64(55.67215568862275)

In [45]:
## Assign a variable to the initial code to find the mean
mean_age = df['Age'].mean()      ## the variable name is the mean_age
print(mean_age)

55.67215568862275


In [46]:
## Using the value for the highest_count to fix the missing value
df['Age'] = df['Age'].fillna(mean_age)

In [47]:
## Checking if the change has been affected
df.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [48]:
## Imputing / fixing the missing value for Column Label[KM] 
## We are using the function fillna()
## The datatype for KM is object therefore we will use value_counts() to determine its value KM column
df['KM'].value_counts()

KM
1        8
59000    7
36000    7
43000    7
45000    6
        ..
42000    1
47955    1
47633    1
47400    1
47360    1
Name: count, Length: 1255, dtype: int64

In [49]:
## Selecting the hightest value count from KM column
highest_count = df['KM'].value_counts().index[0]  ## Using index to select the highest_count
print(highest_count)

1


In [50]:
## Using the value for the highest_count to fix the missing value
df['KM'] = df['KM'].fillna(highest_count)

In [51]:
## Checking if the change has taken place
df.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [53]:
## Imputing / fixing the missing value for Column Label[FuelType] 
## We are using the function fillna()
## The datatype for FuelType is object therefore we will use value_counts() to determine its value FuelType column
df['FuelType'].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [54]:
## Selecting the hightest value count from FuelType column
highest_value = df['FuelType'].value_counts().index[0]   ## Using index to select the highest_value
print(highest_value)

Petrol


In [55]:
## Using the value for the highest_value to fix the missing value
df['FuelType'] = df['FuelType'].fillna(highest_value)

In [56]:
## Checking if the change has taken place
df.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType        0
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [57]:
## Imputing / fixing the missing value for Column Label[HP] 
## We are using the function fillna()
## The datatype for HP is object therefore we will use value_counts() to determine its value HP column
df['HP'].value_counts()

HP
110    833
86     249
97     164
72      72
90      35
69      33
107     21
192     10
116      9
98       2
71       1
73       1
Name: count, dtype: int64

In [58]:
## Selecting the hightest value count from HP column
highest_value = df['HP'].value_counts().index[0]   ## Using index to select the highest_value
print(highest_value)

110


In [59]:
## Using the value for the highest_value to fix the missing value
df['HP'] = df['HP'].fillna(highest_value)

In [60]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType        0
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [61]:
## Imputing / fixing the missing value for Column Label[MetColor] 
## We are using the function fillna()
## The datatype for Age is float, therefore we will use mean to find the average of MetColor column
df['MetColor'].mean()

np.float64(0.6749611197511665)

In [62]:
## Assign a variable to the initial code to find the mean
mean_metcol = df['MetColor'].mean()      ## the variable name is the mean_metcol
print(mean_metcol)

0.6749611197511665


In [63]:
## Using the value for the highest_count to fix the missing value
df['MetColor'] = df['MetColor'].fillna(mean_metcol)

In [64]:
df.isnull().sum()

Unnamed: 0    0
Price         0
Age           0
KM            0
FuelType      0
HP            0
MetColor      0
Automatic     0
CC            0
Doors         0
Weight        0
dtype: int64

In [65]:
## Checking if all the missing values has been fixed
df.head(30)

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel   90  1.000000          0  2000   
1            1  13750  23.0  72937   Diesel   90  1.000000          0  2000   
2            2  13950  24.0  41711   Diesel   90  0.674961          0  2000   
3            3  14950  26.0  48000   Diesel   90  0.000000          0  2000   
4            4  13750  30.0  38500   Diesel   90  0.000000          0  2000   
5            5  12950  32.0  61000   Diesel   90  0.000000          0  2000   
6            6  16900  27.0      1   Diesel  110  0.674961          0  2000   
7            7  18600  30.0  75889   Petrol   90  1.000000          0  2000   
8            8  21500  27.0  19700   Petrol  192  0.000000          0  1800   
9            9  12950  23.0  71138   Diesel  110  0.674961          0  1900   
10          10  20950  25.0  31461   Petrol  192  0.000000          0  1800   
11          11  19950  22.0  43610   Petrol  192  0.000000          0  1800   
12          12  19600  25.0  32189   Petrol  192  0.000000          0  1800   
13          13  21500  31.0  23000   Petrol  192  1.000000          0  1800   
14          14  22500  32.0  34131   Petrol  192  1.000000          0  1800   
15          15  22000  28.0  18739   Petrol  110  0.000000          0  1800   
16          16  22750  30.0  34000   Petrol  192  1.000000          0  1800   
17          17  17950  24.0  21716   Petrol  110  1.000000          0  1600   
18          18  16750  24.0  25563   Petrol  110  0.000000          0  1600   
19          19  16950  30.0  64359   Petrol  110  1.000000          0  1600   
20          20  15950  30.0  67660   Petrol  110  1.000000          0  1600   
21          21  16950  29.0  43905   Petrol  110  0.000000          1  1600   
22          22  15950  28.0  56349   Petrol  110  1.000000          0  1600   
23          23  16950  28.0  32220   Petrol  110  1.000000          0  1600   
24          24  16250  29.0  25813   Petrol  110  1.000000          0  1600   
25          25  15950  25.0  28450   Petrol  110  1.000000          0  1600   
26          26  17495  27.0  34545   Petrol  110  1.000000          0  1600   
27          27  15750  29.0  41415   Petrol  110  1.000000          0  1600   
28          28  16950  28.0  44142   Petrol  110  0.000000          0  1600   
29          29  17950  30.0  11090   Petrol  110  0.674961          0  1600   

    Doors  Weight  
0   three    1165  
1       3    1165  
2       3    1165  
3       3    1165  
4       3    1170  
5       3    1170  
6       3    1245  
7       3    1245  
8       3    1185  
9       3    1105  
10      3    1185  
11      3    1185  
12      3    1185  
13      3    1185  
14      3    1185  
15      3    1185  
16      3    1185  
17      3    1105  
18      3    1065  
19      3    1105  
20      3    1105  
21      3    1170  
22      3    1120  
23      3    1120  
24      3    1120  
25      3    1120  
26      3    1120  
27      3    1120  
28      3    1120  
29      3    1120

In [69]:
## Replacing the objects in the Doors column with integers
df['Doors'] = df['Doors'].replace('three',3)

In [70]:
df['Doors'].unique()

array([3, '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [71]:
## Replacing the objects in the Doors column with integers
df['Doors'] = df['Doors'].replace('four',4)

In [ ]:
df['Doors'].unique()

In [72]:
## Replacing the objects in the Doors column with integers
df['Doors'] = df['Doors'].replace('five',5)

In [73]:
df['Doors'].unique()

array([3, '3', '5', '4', 4, 5, '2'], dtype=object)

In [74]:
df.head(30)

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel   90  1.000000          0  2000   
1            1  13750  23.0  72937   Diesel   90  1.000000          0  2000   
2            2  13950  24.0  41711   Diesel   90  0.674961          0  2000   
3            3  14950  26.0  48000   Diesel   90  0.000000          0  2000   
4            4  13750  30.0  38500   Diesel   90  0.000000          0  2000   
5            5  12950  32.0  61000   Diesel   90  0.000000          0  2000   
6            6  16900  27.0      1   Diesel  110  0.674961          0  2000   
7            7  18600  30.0  75889   Petrol   90  1.000000          0  2000   
8            8  21500  27.0  19700   Petrol  192  0.000000          0  1800   
9            9  12950  23.0  71138   Diesel  110  0.674961          0  1900   
10          10  20950  25.0  31461   Petrol  192  0.000000          0  1800   
11          11  19950  22.0  43610   Petrol  192  0.000000          0  1800   
12          12  19600  25.0  32189   Petrol  192  0.000000          0  1800   
13          13  21500  31.0  23000   Petrol  192  1.000000          0  1800   
14          14  22500  32.0  34131   Petrol  192  1.000000          0  1800   
15          15  22000  28.0  18739   Petrol  110  0.000000          0  1800   
16          16  22750  30.0  34000   Petrol  192  1.000000          0  1800   
17          17  17950  24.0  21716   Petrol  110  1.000000          0  1600   
18          18  16750  24.0  25563   Petrol  110  0.000000          0  1600   
19          19  16950  30.0  64359   Petrol  110  1.000000          0  1600   
20          20  15950  30.0  67660   Petrol  110  1.000000          0  1600   
21          21  16950  29.0  43905   Petrol  110  0.000000          1  1600   
22          22  15950  28.0  56349   Petrol  110  1.000000          0  1600   
23          23  16950  28.0  32220   Petrol  110  1.000000          0  1600   
24          24  16250  29.0  25813   Petrol  110  1.000000          0  1600   
25          25  15950  25.0  28450   Petrol  110  1.000000          0  1600   
26          26  17495  27.0  34545   Petrol  110  1.000000          0  1600   
27          27  15750  29.0  41415   Petrol  110  1.000000          0  1600   
28          28  16950  28.0  44142   Petrol  110  0.000000          0  1600   
29          29  17950  30.0  11090   Petrol  110  0.674961          0  1600   

   Doors  Weight  
0      3    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170  
5      3    1170  
6      3    1245  
7      3    1245  
8      3    1185  
9      3    1105  
10     3    1185  
11     3    1185  
12     3    1185  
13     3    1185  
14     3    1185  
15     3    1185  
16     3    1185  
17     3    1105  
18     3    1065  
19     3    1105  
20     3    1105  
21     3    1170  
22     3    1120  
23     3    1120  
24     3    1120  
25     3    1120  
26     3    1120  
27     3    1120  
28     3    1120  
29     3    1120

In [75]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM              int64
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

## Converting the datatypes for KM,HP and Doors to integer datatypes

In [ ]:
## Converting the KM datatype(object) to integer
df['KM'] = df['KM'].astype('int64')

In [76]:
## Converting the HP datatype(object) to integer
df['HP'] = df['HP'].astype('int64')

In [77]:
## Converting the Doors datatype(object) to integer
df['Doors'] = df['Doors'].astype('int64')

In [78]:
## Checking the datatpyes to their correct types
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM              int64
FuelType       object
HP              int64
MetColor      float64
Automatic       int64
CC              int64
Doors           int64
Weight          int64
dtype: object