In [2]:
## Import pandas and numpy
import pandas as pd
import numpy as np

In [3]:
## Loading of data
data1=pd.read_csv("Datasets/Toyota.csv")
data1
df=data1.copy(deep=True)

In [4]:
## head (30): Display first Thirty rows
df.head(30)

Unnamed: 0  Price   Age     KM FuelType    HP  MetColor  Automatic    CC  \
0            0  13500  23.0  46986   Diesel    90       1.0          0  2000   
1            1  13750  23.0  72937   Diesel    90       1.0          0  2000   
2            2  13950  24.0  41711   Diesel    90       NaN          0  2000   
3            3  14950  26.0  48000   Diesel    90       0.0          0  2000   
4            4  13750  30.0  38500   Diesel    90       0.0          0  2000   
5            5  12950  32.0  61000   Diesel    90       0.0          0  2000   
6            6  16900  27.0     ??   Diesel  ????       NaN          0  2000   
7            7  18600  30.0  75889      NaN    90       1.0          0  2000   
8            8  21500  27.0  19700   Petrol   192       0.0          0  1800   
9            9  12950  23.0  71138   Diesel  ????       NaN          0  1900   
10          10  20950  25.0  31461   Petrol   192       0.0          0  1800   
11          11  19950  22.0  43610   Petrol   192       0.0          0  1800   
12          12  19600  25.0  32189   Petrol   192       0.0          0  1800   
13          13  21500  31.0  23000   Petrol   192       1.0          0  1800   
14          14  22500  32.0  34131   Petrol   192       1.0          0  1800   
15          15  22000  28.0  18739   Petrol  ????       0.0          0  1800   
16          16  22750  30.0  34000   Petrol   192       1.0          0  1800   
17          17  17950  24.0  21716   Petrol   110       1.0          0  1600   
18          18  16750  24.0  25563   Petrol   110       0.0          0  1600   
19          19  16950  30.0  64359   Petrol   110       1.0          0  1600   
20          20  15950  30.0  67660   Petrol   110       1.0          0  1600   
21          21  16950  29.0  43905      NaN   110       0.0          1  1600   
22          22  15950  28.0  56349   Petrol   110       1.0          0  1600   
23          23  16950  28.0  32220   Petrol   110       1.0          0  1600   
24          24  16250  29.0  25813   Petrol   110       1.0          0  1600   
25          25  15950  25.0  28450   Petrol   110       1.0          0  1600   
26          26  17495  27.0  34545      NaN   110       1.0          0  1600   
27          27  15750  29.0  41415   Petrol   110       1.0          0  1600   
28          28  16950  28.0  44142   Petrol   110       0.0          0  1600   
29          29  17950  30.0  11090      NaN   110       NaN          0  1600   

    Doors  Weight  
0   three    1165  
1       3    1165  
2       3    1165  
3       3    1165  
4       3    1170  
5       3    1170  
6       3    1245  
7       3    1245  
8       3    1185  
9       3    1105  
10      3    1185  
11      3    1185  
12      3    1185  
13      3    1185  
14      3    1185  
15      3    1185  
16      3    1185  
17      3    1105  
18      3    1065  
19      3    1105  
20      3    1105  
21      3    1170  
22      3    1120  
23      3    1120  
24      3    1120  
25      3    1120  
26      3    1120  
27      3    1120  
28      3    1120  
29      3    1120

In [5]:
## Tail (30): Display last thirty rows
df.tail(30)

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1406        1406   8950  70.0  44850   Petrol  110       1.0          0  1600   
1407        1407   8250  69.0  44826   Petrol  110       0.0          0  1600   
1408        1408   9250   NaN  44444   Petrol  110       1.0          0  1600   
1409        1409   7900  75.0  43720   Petrol  110       NaN          0  1600   
1410        1410   8500  78.0  43622   Petrol   86       1.0          0  1300   
1411        1411   7950  76.0  43532   Petrol  110       0.0          0  1600   
1412        1412   9950  69.0  42800   Petrol  110       1.0          0  1600   
1413        1413   8750  74.0  42317   Petrol  107       1.0          1  1600   
1414        1414   7500  80.0  42186   Petrol  110       1.0          0  1600   
1415        1415   6950  72.0  42000   Petrol  110       NaN          0  1600   
1416        1416   8950   NaN  40093   Petrol  110       0.0          0  1600   
1417        1417   8750  79.0  39800   Petrol  107       0.0          1  1600   
1418        1418   7750  73.0  39168   Petrol   86       NaN          0  1300   
1419        1419   8450  75.0  38945   Petrol  110       NaN          0  1600   
1420        1420   8150  76.0  36537      NaN  110       0.0          1  1600   
1421        1421   8500  78.0     ??   Petrol   86       0.0          1  1300   
1422        1422   7600   NaN  36000      NaN  110       1.0          0  1600   
1423        1423   7950  80.0  35821   Petrol   86       0.0          1  1300   
1424        1424   7750  73.0  34717   Petrol   86       0.0          0  1300   
1425        1425   7950  80.0     ??   Petrol   86       1.0          0  1300   
1426        1426   9950  78.0  30964   Petrol  110       NaN          1  1600   
1427        1427   8950   NaN  29000   Petrol   86       1.0          1  1300   
1428        1428   8450  72.0     ??   Petrol   86       NaN          0  1300   
1429        1429   8950  78.0  24000   Petrol   86       1.0          1  1300   
1430        1430   8450  80.0  23000   Petrol   86       0.0          0  1300   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1406     3    1050  
1407     5    1075  
1408     3    1050  
1409     5    1070  
1410     4    1000  
1411     5    1070  
1412     3    1050  
1413     5    1100  
1414     3    1050  
1415     3    1050  
1416     5    1114  
1417     3    1080  
1418     3    1015  
1419     3    1050  
1420     4    1075  
1421     3    1045  
1422     3    1050  
1423     3    1015  
1424     3    1015  
1425     4    1000  
1426     3    1080  
1427     3    1045  
1428     3    1015  
1429     5    1065  
1430     3    1015  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

In [6]:
## Shape: Returns the shape of the datasets
df.shape

(1436, 11)

In [7]:
## Size: Returns the size of datasets
df.size

15796

In [61]:
## iloc: Look for data in between datasets
df.iloc[10:30,]


Unnamed: 0  Price   Age       KM FuelType          HP  MetColor  \
10          10  20950  25.0  31461.0   Petrol  192.000000       0.0   
11          11  19950  22.0  43610.0   Petrol  192.000000       0.0   
12          12  19600  25.0  32189.0   Petrol  192.000000       0.0   
13          13  21500  31.0  23000.0   Petrol  192.000000       1.0   
14          14  22500  32.0  34131.0   Petrol  192.000000       1.0   
15          15  22000  28.0  18739.0   Petrol  101.478322       0.0   
16          16  22750  30.0  34000.0   Petrol  192.000000       1.0   
17          17  17950  24.0  21716.0   Petrol  110.000000       1.0   
18          18  16750  24.0  25563.0   Petrol  110.000000       0.0   
19          19  16950  30.0  64359.0   Petrol  110.000000       1.0   
20          20  15950  30.0  67660.0   Petrol  110.000000       1.0   
21          21  16950  29.0  43905.0   Petrol  110.000000       0.0   
22          22  15950  28.0  56349.0   Petrol  110.000000       1.0   
23          23  16950  28.0  32220.0   Petrol  110.000000       1.0   
24          24  16250  29.0  25813.0   Petrol  110.000000       1.0   
25          25  15950  25.0  28450.0   Petrol  110.000000       1.0   
26          26  17495  27.0  34545.0   Petrol  110.000000       1.0   
27          27  15750  29.0  41415.0   Petrol  110.000000       1.0   
28          28  16950  28.0  44142.0   Petrol  110.000000       0.0   
29          29  17950  30.0  11090.0   Petrol  110.000000       1.0   

    Automatic    CC Doors  Weight  
10          0  1800     3    1185  
11          0  1800     3    1185  
12          0  1800     3    1185  
13          0  1800     3    1185  
14          0  1800     3    1185  
15          0  1800     3    1185  
16          0  1800     3    1185  
17          0  1600     3    1105  
18          0  1600     3    1065  
19          0  1600     3    1105  
20          0  1600     3    1105  
21          1  1600     3    1170  
22          0  1600     3    1120  
23          0  1600     3    1120  
24          0  1600     3    1120  
25          0  1600     3    1120  
26          0  1600     3    1120  
27          0  1600     3    1120  
28          0  1600     3    1120  
29          0  1600     3    1120

In [64]:
## Access a single value for a row or column by their lable or index
df.at[10,'Price'] ## Lable


np.int64(20950)

In [9]:
Tuple1=df.shape
a,b=Tuple1
print(a)
print(b)

1436
11


In [10]:
## Fnding the total number of rows and columns in a meaningful way
print("Total number of rows:",df.shape[0],  "Total Number of Columns:", df.shape[1])


Total number of rows: 1436 Total Number of Columns: 11


In [11]:
## Info: Display a concise summary of the datasets
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [12]:
## dtypes :return the columns and their data types
df.dtypes


Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [13]:
## Unique:  Return the number of unique values in each column
data1['Price'].unique()

array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,

In [14]:
data1['FuelType'].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [15]:
data1['CC'].unique()

array([2000, 1800, 1900, 1600, 1400, 1598, 1995, 1398, 1300, 1587, 1975,
       1332])

In [16]:
df['Doors'].unique()

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [17]:
df['Weight'].unique()

array([1165, 1170, 1245, 1185, 1105, 1065, 1120, 1100, 1255, 1270, 1110,
       1195, 1180, 1075, 1130, 1275, 1060, 1115, 1265, 1260, 1125, 1155,
       1045, 1480, 1320, 1280, 1135, 1090, 1150, 1085, 1160, 1205, 1084,
       1140, 1095, 1025, 1119, 1080, 1121, 1615, 1067, 1040, 1030, 1055,
       1050, 1103, 1070, 1035, 1015, 1000, 1078, 1079, 1109, 1020, 1010,
       1114, 1172, 1094, 1083])

In [18]:
## Isnull: returns the number of missing values in each column
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [19]:
## Unique Value
df['Age'].unique()

array([23., 24., 26., 30., 32., 27., 25., 22., 31., 28., 29., nan, 20.,
       19., 17., 11., 18., 13., 14.,  4.,  8.,  7., 16., 15., 10., 12.,
        9.,  6.,  2.,  1., 43., 38., 40., 44., 41., 37., 39., 42., 35.,
       34., 33., 36., 53., 51., 54., 45., 55., 48., 52., 49., 56., 50.,
       47., 46., 58., 68., 59., 62., 65., 67., 64., 60., 61., 66., 57.,
       63., 73., 79., 78., 74., 77., 69., 80., 76., 70., 71., 75., 72.])

In [20]:
df['FuelType'].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [21]:
df['MetColor'].unique()

array([ 1., nan,  0.])

In [22]:
## Replacing of special characters
data1['KM'].replace("??", np.nan, inplace=False)

0       46986
1       72937
2       41711
3       48000
4       38500
        ...  
1431    20544
1432      NaN
1433    17016
1434      NaN
1435        1
Name: KM, Length: 1436, dtype: object

In [23]:
data1['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [24]:
# Replace with missing value
df['KM'] = df['KM'].replace("??",np.nan)


In [25]:
df['KM'].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [26]:
## Convert datatype to float in KM
df['KM'].astype('float64')

0       46986.0
1       72937.0
2       41711.0
3       48000.0
4       38500.0
         ...   
1431    20544.0
1432        NaN
1433    17016.0
1434        NaN
1435        1.0
Name: KM, Length: 1436, dtype: float64

In [27]:
## Checking the type  of data in the dataset
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [28]:
## Changing datatype 'object' in KM Column to float64
df['KM'] =df['KM'].astype('float64')

In [29]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [30]:
## HP Column; Replace of special characters
df['HP'] = df['HP'].replace("????",np.nan)

In [31]:
## confirming if 'nan' has worked
df['HP'].unique()

array(['90', nan, '192', '110', '97', '71', '116', '98', '69', '86', '72',
       '107', '73'], dtype=object)

In [32]:
data1['HP'].replace("????", np.nan, inplace=False)

0        90
1        90
2        90
3        90
4        90
       ... 
1431     86
1432     86
1433     86
1434     86
1435    110
Name: HP, Length: 1436, dtype: object

In [33]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [34]:
## Changing the datatype to float64 in HP column
df['HP'].astype('float64')

0        90.0
1        90.0
2        90.0
3        90.0
4        90.0
        ...  
1431     86.0
1432     86.0
1433     86.0
1434     86.0
1435    110.0
Name: HP, Length: 1436, dtype: float64

In [35]:
## Confirming if has changed
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [36]:
df['HP'] =df['HP'].astype('float64')

In [37]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM            float64
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [38]:
## Checking for Null values
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [39]:
## fixing of missing values for KM
mean_KM =df['KM'].mean()
print(mean_KM)

68647.23997185081


In [40]:
## Fillna: Fill all missing values
df['KM'].fillna(mean_KM)

0       46986.000000
1       72937.000000
2       41711.000000
3       48000.000000
4       38500.000000
            ...     
1431    20544.000000
1432    68647.239972
1433    17016.000000
1434    68647.239972
1435        1.000000
Name: KM, Length: 1436, dtype: float64

In [41]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [42]:
df['KM'] =df['KM'].fillna(mean_KM)

In [43]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [44]:
## Fixing missing Values in HP
mean_HP =df['HP'].mean()
print(mean_HP)

101.47832167832168


In [45]:
## Fillna: Fill all missing values
df['HP'].fillna(mean_HP)

0        90.0
1        90.0
2        90.0
3        90.0
4        90.0
        ...  
1431     86.0
1432     86.0
1433     86.0
1434     86.0
1435    110.0
Name: HP, Length: 1436, dtype: float64

In [46]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [47]:
## Fixing all missing values in HP with the mean
df['HP'] =df['HP'].fillna(mean_HP)

In [48]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [49]:
## fixing missing values for FuelType columns
df['FuelType'].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [50]:
## selecting  the value with the highest count
highest_count= df['FuelType'].value_counts().index[0]

In [51]:
## replace it in the column
df['FuelType']=df['FuelType'].fillna(highest_count)
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType        0
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [52]:
## fixing missing values for Age columns
df['Age'].value_counts()

Age
65.0    62
68.0    60
80.0    52
62.0    41
78.0    41
        ..
15.0     2
18.0     1
10.0     1
6.0      1
2.0      1
Name: count, Length: 77, dtype: int64

In [53]:
## selecting  the value with the highest count
highest_count= df['Age'].value_counts().index[0]

In [54]:
## replace it in the column
df['Age']=df['Age'].fillna(highest_count)
df.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType        0
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [55]:
## fixing missing values for MetColor columns
df['MetColor'].value_counts()

MetColor
1.0    868
0.0    418
Name: count, dtype: int64

In [56]:
## selecting  the value with the highest count
highest_count= df['MetColor'].value_counts().index[0]

In [57]:
## replace it in the column
df['MetColor']=df['MetColor'].fillna(highest_count)
df.isnull().sum()

Unnamed: 0    0
Price         0
Age           0
KM            0
FuelType      0
HP            0
MetColor      0
Automatic     0
CC            0
Doors         0
Weight        0
dtype: int64