In [1]:
import pandas as pd
import numpy as np

In [2]:
data_nice = pd.read_csv("Datasets/Toyota.csv")
data_nice

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

## READING /CREATING A COPY OF DATASETS

In [3]:
##  Creating a copy of datasets
dn1 = data_nice.copy(deep=True)
dn1

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000   
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000   
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000   
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000   
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000   
...          ...    ...   ...    ...      ...  ...       ...        ...   ...   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

      Doors  Weight  
0     three    1165  
1         3    1165  
2         3    1165  
3         3    1165  
4         3    1170  
...     ...     ...  
1431      3    1025  
1432      3    1015  
1433      3    1015  
1434      3    1015  
1435      5    1114  

[1436 rows x 11 columns]

## Understanding Datasets

In [4]:
## Display the first ten rows
dn1.head(10)

Unnamed: 0  Price   Age     KM FuelType    HP  MetColor  Automatic    CC  \
0           0  13500  23.0  46986   Diesel    90       1.0          0  2000   
1           1  13750  23.0  72937   Diesel    90       1.0          0  2000   
2           2  13950  24.0  41711   Diesel    90       NaN          0  2000   
3           3  14950  26.0  48000   Diesel    90       0.0          0  2000   
4           4  13750  30.0  38500   Diesel    90       0.0          0  2000   
5           5  12950  32.0  61000   Diesel    90       0.0          0  2000   
6           6  16900  27.0     ??   Diesel  ????       NaN          0  2000   
7           7  18600  30.0  75889      NaN    90       1.0          0  2000   
8           8  21500  27.0  19700   Petrol   192       0.0          0  1800   
9           9  12950  23.0  71138   Diesel  ????       NaN          0  1900   

   Doors  Weight  
0  three    1165  
1      3    1165  
2      3    1165  
3      3    1165  
4      3    1170  
5      3    1170  
6      3    1245  
7      3    1245  
8      3    1185  
9      3    1105

In [5]:
## Display the last ten(10) rows
dn1.tail(10)

Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
1426        1426   9950  78.0  30964   Petrol  110       NaN          1  1600   
1427        1427   8950   NaN  29000   Petrol   86       1.0          1  1300   
1428        1428   8450  72.0     ??   Petrol   86       NaN          0  1300   
1429        1429   8950  78.0  24000   Petrol   86       1.0          1  1300   
1430        1430   8450  80.0  23000   Petrol   86       0.0          0  1300   
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300   
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300   
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300   
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300   
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600   

     Doors  Weight  
1426     3    1080  
1427     3    1045  
1428     3    1015  
1429     5    1065  
1430     3    1015  
1431     3    1025  
1432     3    1015  
1433     3    1015  
1434     3    1015  
1435     5    1114

In [6]:
## Display the types of columns
dn1.columns

Index(['Unnamed: 0', 'Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor',
       'Automatic', 'CC', 'Doors', 'Weight'],
      dtype='object')

In [7]:
## Displaying all types of columns in lower case
for each_item in dn1.columns:
    print(each_item.lower())

unnamed: 0
price
age
km
fueltype
hp
metcolor
automatic
cc
doors
weight


In [8]:
## Displaying all types of columns in lower case
for each_item in dn1.columns:
    print(each_item.upper())

UNNAMED: 0
PRICE
AGE
KM
FUELTYPE
HP
METCOLOR
AUTOMATIC
CC
DOORS
WEIGHT


In [9]:
## Displya the values in a column
dn1["Age"]

0       23.0
1       23.0
2       24.0
3       26.0
4       30.0
        ... 
1431     NaN
1432    72.0
1433     NaN
1434    70.0
1435    76.0
Name: Age, Length: 1436, dtype: float64

In [10]:
## Assessing a single cell for a row or column by thier index and label
#dn1.at[1,"Age"]

In [11]:
dn1.iat[1,2]

np.float64(23.0)

In [12]:
## Assessing a group or rows and column by their label
dn1.loc[1:20,"Age"]

1     23.0
2     24.0
3     26.0
4     30.0
5     32.0
6     27.0
7     30.0
8     27.0
9     23.0
10    25.0
11    22.0
12    25.0
13    31.0
14    32.0
15    28.0
16    30.0
17    24.0
18    24.0
19    30.0
20    30.0
Name: Age, dtype: float64

In [13]:
dn1.iloc[2,1] 

np.int64(13950)

In [14]:
## Return the shape of the dataset
dn1.shape

(1436, 11)

In [15]:
##Returns the size of the datasets
dn1.size

15796

In [16]:
print(f"Total number of rows is {dn1.shape[0]} and the Total number of columns is {dn1.shape[1]}")

Total number of rows is 1436 and the Total number of columns is 11


In [17]:
## Returns a concise summary of data
dn1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [18]:
## Returns the types of fuel in the colum'FuelType'
dn1["FuelType"].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [19]:
dn1["Price"].unique()

array([13500, 13750, 13950, 14950, 12950, 16900, 18600, 21500, 20950,
       19950, 19600, 22500, 22000, 22750, 17950, 16750, 16950, 15950,
       16250, 17495, 15750, 15500, 14750, 19000, 15800, 21950, 20500,
       13250, 15250, 18950, 15999, 16500, 18750, 22250, 12995, 18450,
       16895, 14900, 17250, 15450, 16650, 17450, 16450, 18900, 18990,
       18500, 19450, 18800, 32500, 31000, 31275, 24950, 22950, 24990,
       17900, 19250, 16350, 21750, 15850, 23000, 19900, 23950, 24500,
       17200, 19500, 16868, 19750, 20750, 17650, 17795, 18245, 23750,
       18700, 21125,  6950,  9500, 11950,  7750,  4350,  4750, 11750,
       11900,  9950, 11495, 11250, 10500, 10450, 11500, 12500, 10950,
       11450, 11790, 12450, 11690, 12750, 11925, 12900, 11650, 10850,
        9940, 13450, 12495, 12000, 11480, 14990, 12850, 11700, 11895,
       13875, 12295, 13995,  9900, 11990, 10750, 11695, 11000, 12400,
       12200, 12695, 14350, 10250,  6500,  6400,  7000,  8900,  8500,
        8950,  9250,

In [20]:
dn1["HP"].unique()

array(['90', '????', '192', '110', '97', '71', '116', '98', '69', '86',
       '72', '107', '73'], dtype=object)

In [21]:
dn1["MetColor"].unique()

array([ 1., nan,  0.])

In [22]:
dn1["Weight"].unique()

array([1165, 1170, 1245, 1185, 1105, 1065, 1120, 1100, 1255, 1270, 1110,
       1195, 1180, 1075, 1130, 1275, 1060, 1115, 1265, 1260, 1125, 1155,
       1045, 1480, 1320, 1280, 1135, 1090, 1150, 1085, 1160, 1205, 1084,
       1140, 1095, 1025, 1119, 1080, 1121, 1615, 1067, 1040, 1030, 1055,
       1050, 1103, 1070, 1035, 1015, 1000, 1078, 1079, 1109, 1020, 1010,
       1114, 1172, 1094, 1083])

In [23]:
## Returns the number of missing numbres in each column
dn1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [24]:
## Returns columns and their types 
dn1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [25]:
## Returns the number of unique values in each column
dn1.nunique()

Unnamed: 0    1436
Price          236
Age             77
KM            1256
FuelType         3
HP              13
MetColor         2
Automatic        2
CC              12
Doors            7
Weight          59
dtype: int64

In [26]:
## Returns the types of fuel in the column"FuelType'
dn1.nunique()

Unnamed: 0    1436
Price          236
Age             77
KM            1256
FuelType         3
HP              13
MetColor         2
Automatic        2
CC              12
Doors            7
Weight          59
dtype: int64

In [27]:
##Returns the types of fuel in the column "FuelType"
dn1["FuelType"].unique()

array(['Diesel', nan, 'Petrol', 'CNG'], dtype=object)

In [29]:
## Fixing missing values
dn1["FuelType"].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

In [31]:
dn1["FuelType"].value_counts().index[0]

'Petrol'

In [35]:
## selecting the value with the highest count and replacing it in the column 
highest_count = dn1["FuelType"].value_counts().index[0]
dn1["FuelType"] = dn1["FuelType"].fillna(highest_count)

In [36]:
dn1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType        0
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

## DATA PROCESSING

In [37]:
## Replacing special characters
dn1["KM"] = dn1["KM"].replace("??" , np.nan)
dn1["KM"].unique()

array(['46986', '72937', '41711', ..., '30964', '20544', '17016'],
      dtype=object)

In [38]:
## converting column data to float
dn1["KM"].astype("float64")

0       46986.0
1       72937.0
2       41711.0
3       48000.0
4       38500.0
         ...   
1431    20544.0
1432        NaN
1433    17016.0
1434        NaN
1435        1.0
Name: KM, Length: 1436, dtype: float64

In [39]:
dn1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [45]:
dn1["HP"]=dn1["HP"].replace("????" , np.nan)
dn1["HP"].unique()

array(['90', nan, '192', '110', '97', '71', '116', '98', '69', '86', '72',
       '107', '73'], dtype=object)

In [46]:
dn1["HP"]=dn1["HP"].astype("float")
dn1.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP            float64
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [47]:
## Return the number of missing value in each column
dn1.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM             15
FuelType        0
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [48]:
## Fixing values for Age
mean_age = dn1["Age"].mean()
print(mean_age)

55.67215568862275


In [49]:
## Fill in the missing value using Fillna
dn1["Age"].fillna(mean_age)

0       23.000000
1       23.000000
2       24.000000
3       26.000000
4       30.000000
          ...    
1431    55.672156
1432    72.000000
1433    55.672156
1434    70.000000
1435    76.000000
Name: Age, Length: 1436, dtype: float64

dn1.isnull().sum()

In [51]:
dn1["Age"] = dn1["Age"].fillna(mean_age)

In [52]:
dn1.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM             15
FuelType        0
HP              6
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64